---
- name: Basic setup for camsible
  hosts: localhost
  become: yes
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Install stuff!
      apt:
        name: 
          - curl
          - zsh
          - git
          - vim
          - tmux
          - htop
          - tree
          - python3-pip
          - neovim
        state: present

#log the current user
    - name: log the current user
      debug:
        msg: "Current user is {{ ansible_env.USER }}"
        
    - name: make zsh the default shell
      user:
        name: "{{ ansible_env.USER }}"
        shell: /bin/zsh