- name: Basic setup for camsible
  hosts: localhost
  become: yes
  tasks:
    - name: Create the 'cam' user
      user:
        name: cam
        shell: /bin/zsh
        create_home: yes
        generate_ssh_key: true
        group: cam
        groups: sudo
        append: yes

    - name: Add 'cam' user to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'cam ALL=(ALL) NOPASSWD:ALL'

    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Install essential packages
      apt:
        name: 
          - curl
          - zsh
          - git
          - vim
          - tmux
          - htop
          - tree
          - python3-pip
          - neovim
        state: present