- name: Ensure stow is installed
  apt:
    name: stow
    state: present
  become: true

- name: Clone dotfiles repository
  git:
    repo: 'https://github.com/c-mco/dotfiles.git'
    dest: /home/{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}/dotfiles
    version: main
  become: false

