- name: set zsh as default shell for original user
  become: yes
  user:
    name: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    shell: /bin/zsh

- name: Clone dotfiles repository
  git:
    repo: git@github.com:c-mco/dotfiles.git
    dest: ~/.dotfiles

- name: use stow to symlink dotfiles
  shell: |
    stow -t ~ -d ~/.dotfiles git nvim p10k zsh gh poshthemes 

- name: install Oh My Posh
  shell: |
    curl -s https://ohmyposh.dev/install.sh | bash -s
