- name: Install Zsh
  apt:
    name: zsh
    state: present
  become: true

- name: Set the default shell for the user
  user:
    name: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    shell: /usr/bin/zsh
  become: true

