- name: Install GitHub CLI
  become: true
  block:
    - name: Add GitHub CLI repository key
      apt_key:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        state: present

    - name: Add GitHub CLI repository
      apt_repository:
        repo: deb   
 [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main   

        state: present
        filename: github-cli

    - name:   
 Update apt cache
      apt:
        update_cache: yes

    - name: Install gh package
      apt:
        name: gh
        state: present
        
- name: Install essential packages
  apt:
    name:
      - build-essential
      - git
      - curl
      - wget
      - zsh
      - tmux
      - stow
      - neovim

- name: Install Oh My Zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh

- name: Set the default shell for the user
  become: true
  user:
    name: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    shell: /usr/bin/zsh
