- name: Install GitHub CLI
  become: true
  block:
    - name: Ensure GPG is installed
      ansible.builtin.apt:
        name: gpg-agent
        state: present

    - name: Add GitHub CLI key
      ansible.builtin.apt_key:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        state: present
        validate_certs: true
        keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg

    - name: Add GitHub CLI repository   

      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages   
 stable main"
        state: present
        filename: github-cli

    - name: Install gh package
      ansible.builtin.apt:
        name: gh
        state: present
        update_cache: true

- name: Install essential packages
  apt:
    name:
      - build-essential
      - git
      - curl
      - wget
      - zsh
      - tmux
      - stow
      - neovim
    state: present
    update_cache: yes

- name: Set the default shell for the user
  user:
    name: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    shell: /usr/bin/zsh

- name: Install Oh My Zsh
  become: false 
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

- name: Install Zsh plugins
  become: false 
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
- name: Install Zsh plugins
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/plugins/zsh-syntax-highlighting

- name: Install nvm
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | sh
    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

- name: Install node LTS
  shell: nvm install --lts
