- name: Install essential packages
  apt:
    name:
      - build-essential
      - git
      - curl
      - wget
      - zsh
      - tmux
      - stow
      - neovim

- name: Install Oh My Zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh

- name: Set the default shell for the user
  become: true
  user:
    name: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    shell: /usr/bin/zsh
