- name: Install dependencies for nvm
  become: yes
  apt:
    name: 
      - curl
      - build-essential
    state: present

- name: Download and install nvm
  become: yes
  become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
  shell: 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash'
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    executable: /bin/bash

- name: Install LTS version of Node.js
  become: yes
  become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
  shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts'
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node"
    chdir: "{{ ansible_env.HOME }}"
    executable: /bin/bash

- name: Set default Node.js version
  become: yes
  become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
  shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm alias default lts/*'
  args:
    executable: /bin/bash

- name: Verify Node.js installation
  become: yes
  become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
  shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && node -v'
  register: node_version
  args:
    executable: /bin/bash

- name: Print Node.js version
  debug:
    msg: "The installed Node.js version is {{ node_version.stdout }}"