- name: Update the package list
  become: true
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  become: true
  apt:
    upgrade: dist

- name: Install essential packages
  become: true
  apt:
    name:
      - build-essential
      - unzip
      - curl
      - zsh
      - git
      - gh
      - vim
      - tmux
      - htop
      - tree
      - python3-pip
      - neovim
      - stow
    state: present

- name: Create user bin dir
  become: true
  become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
  file:
    path: ~/.local/bin
    state: directory
    mode: "0755"

- name: Add user bin dir to PATH
  become: true
  become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
  lineinfile:
    path: ~/.profile
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    create: yes

